### ISSUE TITLE
cwt tracebacks

### ISSUE THREAD

**Issue by phracek** [sclorg/container-workflow-tool#35]
```bash
Traceback (most recent call last):
  File "/usr/local/bin/rhcwt", line 33, in <module>
    sys.exit(load_entry_point('rhcwt==0.5.0', 'console_scripts', 'rhcwt')())
  File "/usr/local/lib/python3.9/site-packages/rh_cwt/cli.py", line 185, in run
    cli.run()
  File "/usr/local/lib/python3.9/site-packages/rh_cwt/cli.py", line 179, in run
    run_function()
  File "/usr/local/lib/python3.9/site-packages/rh_cwt/decorators.py", line 8, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/container_workflow_tool/decorators.py", line 21, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/rh_cwt/main.py", line 496, in dist_git_changes
    super(RhelImageRebuilder, self).dist_git_changes(rebase)
  File "/usr/local/lib/python3.9/site-packages/container_workflow_tool/decorators.py", line 21, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/container_workflow_tool/main.py", line 573, in dist_git_changes
    self.distgit.dist_git_changes(images, rebase)
  File "/usr/local/lib/python3.9/site-packages/container_workflow_tool/distgit.py", line 282, in dist_git_changes
    self.update_dockerfile(
TypeError: update_dockerfile() got an unexpected keyword argument 'downstream_from'
```

**Comment by phracek** [comment]
This is already fixed.
