### ISSUE TITLE
Running tests failed with traceback `KeyError`

### ISSUE THREAD

**Issue by phracek** [sclorg/container-workflow-tool#6]
I tried to run tests by a command:
`make test`

but it fails with traceback
```bash
$ make test
PYTHONPATH=.:$PYTHONPATH python3 -W ignore::DeprecationWarning test//test_brew.py -v
test_get_buildinfo (__main__.BrewTestCase) ... ERROR
test_get_nvr (__main__.BrewTestCase) ... ERROR
test_get_taskinfo (__main__.BrewTestCase) ... ERROR
test_setup_brewapi (__main__.BrewTestCase) ... ERROR

======================================================================
ERROR: test_get_buildinfo (__main__.BrewTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test//test_brew.py", line 7, in setUp
    super(BrewTestCase, self).setUp()
  File "/vagrant/container-workflow-tool/test/common.py", line 29, in setUp
    self.ir.set_config('default.yaml', release="fedora26")
  File "/vagrant/container-workflow-tool/container_workflow_tool/main.py", line 365, in set_config
    newconf = Config(f, release)
  File "/vagrant/container-workflow-tool/container_workflow_tool/config.py", line 64, in __init__
    for key in config[release]:
KeyError: 'fedora26'

======================================================================
ERROR: test_get_nvr (__main__.BrewTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test//test_brew.py", line 7, in setUp
    super(BrewTestCase, self).setUp()
  File "/vagrant/container-workflow-tool/test/common.py", line 29, in setUp
    self.ir.set_config('default.yaml', release="fedora26")
  File "/vagrant/container-workflow-tool/container_workflow_tool/main.py", line 365, in set_config
    newconf = Config(f, release)
  File "/vagrant/container-workflow-tool/container_workflow_tool/config.py", line 64, in __init__
    for key in config[release]:
KeyError: 'fedora26'

======================================================================
ERROR: test_get_taskinfo (__main__.BrewTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test//test_brew.py", line 7, in setUp
    super(BrewTestCase, self).setUp()
  File "/vagrant/container-workflow-tool/test/common.py", line 29, in setUp
    self.ir.set_config('default.yaml', release="fedora26")
  File "/vagrant/container-workflow-tool/container_workflow_tool/main.py", line 365, in set_config
    newconf = Config(f, release)
  File "/vagrant/container-workflow-tool/container_workflow_tool/config.py", line 64, in __init__
    for key in config[release]:
KeyError: 'fedora26'

======================================================================
ERROR: test_setup_brewapi (__main__.BrewTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test//test_brew.py", line 7, in setUp
    super(BrewTestCase, self).setUp()
  File "/vagrant/container-workflow-tool/test/common.py", line 29, in setUp
    self.ir.set_config('default.yaml', release="fedora26")
  File "/vagrant/container-workflow-tool/container_workflow_tool/main.py", line 365, in set_config
    newconf = Config(f, release)
  File "/vagrant/container-workflow-tool/container_workflow_tool/config.py", line 64, in __init__
    for key in config[release]:
KeyError: 'fedora26'

----------------------------------------------------------------------
Ran 4 tests in 0.196s

FAILED (errors=4)
make: *** [Makefile:8: test_brew] Error 1
```

I propose to use Dockerfile.tests for executing tests, so all is isolated.
WDYT?

**Comment by pkubatrh** [comment]
Yes, the tests are in a bad state right now. :/ PRs welcome!

You can add test execution in a container as an alternative to execution on host.

**Comment by phracek** [comment]
I will care about it.

**Comment by phracek** [comment]
This is already fixed, I guess. Closing.
